api_platform:
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json: ['application/json']
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        html: ['text/html']
    swagger:
        versions: [3]
