imports:
    - { resource: ../api_platform/filters/ }

api_platform:
    title: "%app.api.name%"
    version: "%app.api.version%"
    show_webby: false
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: '%env(APP_SECURITY_API_KEY_HEADER_NAME)%'
                type: header

    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json: ['application/json']
        html: ['text/html']

    defaults:
        pagination_enabled: true
        pagination_maximum_items_per_page: 50
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: limit
            page_parameter_name: page
