doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'

    # This is required to ensure BC with previous table name
    # https://github.com/doctrine/migrations/blob/3.0.x/UPGRADE.md
    storage:
        table_storage:
            table_name: migration_versions
