elao_enum:
    # Provide the enum classes for which you want to automatically generate & register Doctrine DBAL Types:
    # https://github.com/Elao/PhpEnums#doctrine
    doctrine:
        types:
            mod_type_enum:
                class: App\Entity\Mod\Enum\ModTypeEnum
            mod_status_enum:
                class: App\Entity\Mod\Enum\ModStatusEnum
            mod_source_enum:
                class: App\Entity\Mod\Enum\ModSourceEnum
