framework:
    http_client:
        scoped_clients:
            client.steam_api:
                scope: 'https://(api|store).steampowered.com'

when@test:
    services:
        client.steam_api:
            class: Symfony\Component\HttpClient\MockHttpClient
            arguments:
                $responseFactory: '@App\Shared\Service\SteamApiClient\Test\SteamApiClientMockResponseFactory'
