twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        url:
            discord: 'https://discord.gg/wcuVSrU'
            steam:   'https://steamcommunity.com/id/armaforces/myworkshopfiles?appid=107410'
            statute: 'https://drive.google.com/file/d/1a2Ote4EegVOxYUP7Un9gosLzBSmWV8fj'
            modlist: 'https://modlist.armaforces.com'
