version: '3.4'

services:

    php:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_php

    nginx:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_nginx
        environment:
            PHP_HOST: php
        depends_on:
            - php
        ports:
            - '8080:80'

    mysql:
        image: mysql:8.0
        container_name: armaforces_mysql
        env_file:
            - .docker/mysql/vars.env
        ports:
            - "33060:3306"
