version: '3.4'

services:

    php:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_php_prod

    nginx:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_nginx
        environment:
            PHP_HOST: php
        depends_on:
            - php
        ports:
            - '8080:80'
