version: '3.4'

services:

    php:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_php
            cache_from:
                - docker.pkg.github.com/armaforces/website/app_assets:dev
                - docker.pkg.github.com/armaforces/website/app_php:dev
        environment:
            APP_ENV: test
        volumes:
            # Copy tests into runtime
            - './.env.test:/www/app/.env.test:ro'
            - './tests:/www/app/tests:rw'
            - './codeception.yml:/www/app/codeception.yml'
            - './.php-cs-fixer.dist.php:/www/app/.php-cs-fixer.dist.php:ro'
            - './phpstan.neon.dist:/www/app/phpstan.neon.dist:ro'
        depends_on:
            - pgsql

    pgsql:
        image: postgres:16.0-alpine
        env_file:
            - .docker/pgsql/vars.env
        environment:
            POSTGRES_DB: 'af_website_test'
        ports:
            - "5432:5432"
