version: '3.4'

services:

    php:
        build:
            target: armaforces_web_php_dev
        volumes:
            - './:/www/app:rw'
            - './var/import:/www/app/var/import:ro'
            - './var/cache:/www/app/var/cache:rw'
        environment:
            # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
            # Then PHPStorm will use the corresponding path mappings
            PHP_IDE_CONFIG: serverName=armaforces-web

    nginx:
        volumes:
            - './public:/www/app/public:ro'

    mysql:
        image: mysql:5.7
        env_file:
            - .docker/mysql/vars.env
        ports:
            - "33060:3306"

    imgproxy:
        image: darthsim/imgproxy:v2
        environment:
            IMGPROXY_KEY: '61726d61'
            IMGPROXY_SALT: '666f72636573'
            IMGPROXY_ENABLE_WEBP_DETECTION: 'true'
            IMGPROXY_MAX_ANIMATION_FRAMES: 900
            IMGPROXY_MAX_SRC_RESOLUTION: 70
            IMGPROXY_TTL: 31536000
            IMGPROXY_WRITE_TIMEOUT: 20
            IMGPROXY_READ_TIMEOUT: 20
        ports:
            - '8888:8080'
