version: '3.4'

services:

    php:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_php
            cache_from:
                - docker.pkg.github.com/armaforces/website/app_php:dev
        volumes:
            # Extract files from runtime for QA tools
            - './var:/www/app/var'
            - './vendor:/www/app/vendor'
            # Copy tests into runtime
            - './.env.test:/www/app/.env.test:ro'
            - './tests:/www/app/tests:ro'
            - './phpunit.xml.dist:/www/app/phpunit.xml.dist:ro'

        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        env_file:
            - .docker/mysql/vars.env
        environment:
            MYSQL_DATABASE: 'af_website_test'
        ports:
            - "3306:3306"
