version: '3.4'

services:

    php:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
            target: armaforces_web_php_dev
            cache_from:
                - docker.pkg.github.com/armaforces/website/app_php:dev
        environment:
            APP_ENV: test
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        env_file:
            - .docker/mysql/vars.env
        environment:
            MYSQL_DATABASE: 'af_website_test'
        ports:
            - "3306:3306"
