resources:
    App\Entity\Attendance\Attendance:
        operations:
            ApiPlatform\Metadata\GetCollection:
                provider: 'App\Api\Provider\Attendance\AttendanceDataProvider'
                output: 'App\Api\Output\Attendance\AttendanceOutput'
                filters:
                    - 'attendance.search_filter'
                    - 'attendance.date_filter'
                    - 'attendance.order_filter'

            ApiPlatform\Metadata\Get:
                provider: 'App\Api\Provider\Attendance\AttendanceDataProvider'
                output: 'App\Api\Output\Attendance\AttendanceOutput'

            ApiPlatform\Metadata\Post:
                input: 'App\Api\Input\Attendance\AttendanceInput'
                processor: 'App\Api\Processor\Attendance\AttendanceProcessor'
                output: 'App\Api\Output\Attendance\AttendanceOutput'
