App\ModManagement\Domain\Model\ModList\ModList:
    attributes:
        output: 'App\ModManagement\UserInterface\Http\Api\Output\ModList\ModListOutput'

    itemOperations:
        get:
            output: 'App\ModManagement\UserInterface\Http\Api\Output\ModList\ModListDetailsOutput'

        get_by_name:
            method: 'GET'
            path: '/mod-lists/by-name/{name}'
            controller: 'App\ModManagement\UserInterface\Http\Api\Controller\GetModListByNameAction'
            output: 'App\ModManagement\UserInterface\Http\Api\Output\ModList\ModListDetailsOutput'
            read: false

    collectionOperations:
        get:
            filters:
                - 'mod_list.search_filter'
                - 'mod_list.date_filter'
                - 'mod_list.order_filter'
