resources:
    App\Entity\ModList\ModList:
        operations:
            ApiPlatform\Metadata\GetCollection:
                provider: 'App\Api\Provider\ModList\ModListDataProvider'
                output: 'App\Api\Output\ModList\ModListOutput'
                filters:
                    - 'mod_list.search_filter'
                    - 'mod_list.date_filter'
                    - 'mod_list.order_filter'

            ApiPlatform\Metadata\Get:
                provider: 'App\Api\Provider\ModList\ModListDetailsDataProvider'
                output: 'App\Api\Output\ModList\ModListDetailsOutput'

            get_by_name:
                output: 'App\Api\Output\ModList\ModListDetailsOutput'
                class: 'ApiPlatform\Metadata\Get'
                uriTemplate: '/mod-lists/by-name/{name}'
                uriVariables:
                    name:
                        fromClass: 'App\Entity\ModList\ModList'
                        fromProperty: 'name'
                controller: 'App\Api\Controller\ModList\GetModListByNameOperation'
                read: false
