# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.organization: ArmaForces
    app.name: "%app.organization% Website"
    app.api.name: "%app.name% Web API"
    app.api.version: '1.0.0'
    app.security.oauth.discord.server_id: '%env(int:APP_SECURITY_OAUTH_DISCORD_SERVER_ID)%'
    app.security.oauth.discord.recruit_role_name: '%env(APP_SECURITY_OAUTH_DISCORD_RECRUIT_ROLE_NAME)%'
    app.security.oauth.discord.member_role_name: '%env(APP_SECURITY_OAUTH_DISCORD_MEMBER_ROLE_NAME)%'
    app.security.oauth.discord.client_id: '%env(APP_SECURITY_OAUTH_DISCORD_CLIENT_ID)%'
    app.security.oauth.discord.client_secret: '%env(APP_SECURITY_OAUTH_DISCORD_CLIENT_SECRET)%'
    app.security.oauth.discord.bot_token: '%env(APP_SECURITY_OAUTH_DISCORD_BOT_TOKEN)%'
    app.security.api.key_header_name: '%env(APP_SECURITY_API_KEY_HEADER_NAME)%'
    app.security.api.allowed_keys: '%env(APP_SECURITY_API_ALLOWED_KEYS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Form\RegisteredDataTransformerInterface:
            tags: [ 'app.form.registered_data_transformer' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Api\Controller\:
        resource: '../src/Api/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Security\Authenticator\DiscordAuthenticator:
        arguments:
            $discordServerId: '%app.security.oauth.discord.server_id%'
            $botToken: '%app.security.oauth.discord.bot_token%'
            $requiredServerRoleNames:
                - '%app.security.oauth.discord.recruit_role_name%'
                - '%app.security.oauth.discord.member_role_name%'

    App\Security\Authenticator\ApiKeyAuthenticator:
        arguments:
            $apiKeyHeaderName: '%app.security.api.key_header_name%'
            $apiAllowedKeys: '%app.security.api.allowed_keys%'

    # Register Doctrine subscribers
    App\EventSubscriber\Doctrine\:
        resource: '../src/EventSubscriber/Doctrine'
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Service\Mission\MissionClient:
        arguments:
            $missionApiUrl: '%env(APP_URL_API_MISSION)%'

    App\Service\Mission\MissionStore:
        arguments:
            $storagePath: '%kernel.project_dir%/var/cache_http/%kernel.environment%'

    App\Service\Version\VersionProvider:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Twig\ImgproxyExtension:
        arguments:
            $baseProxyUrl: '%env(APP_IMGPROXY_URL)%'
            $proxyKey: '%env(APP_IMGPROXY_KEY)%'
            $proxySalt: '%env(APP_IMGPROXY_SALT)%'

    App\Form\DataTransformerRegistry:
        arguments:
            $registeredDataTransformers: !tagged_iterator app.form.registered_data_transformer

    App\Cache\CacheWarmer\BackgroundImageCacheWarmer:
        arguments:
            $backgroundImagesDirectory: '%kernel.project_dir%/public/img/background'

    App\Twig\BackgroundImageExtension:
        arguments:
            $cacheDir: '%kernel.cache_dir%'
