App\Entity\ModList\ModList:
    attributes:
        output: 'App\Api\Dto\ModListOutput'

    itemOperations:
        get:
            output: 'App\Api\Dto\ModListDetailsOutput'
        get_by_name:
            method: 'GET'
            path: '/mod-lists/by-name/{name}'
            controller: 'App\Api\Controller\GetModListByNameAction'
            output: 'App\Api\Dto\ModListDetailsOutput'
            read: false

    collectionOperations:
        get: ~
