name: Docker registry

on:
    push:
        branches:
            - master
            - dev
            - docker-ci

jobs:
    github:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Login to registry
              uses: actions-hub/docker/login@master
              env:
                  DOCKER_USERNAME: ${{ github.actor }}
                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
                  DOCKER_REGISTRY_URL: docker.pkg.github.com
                  REPO_LOWERCASE: armaforces/website

            - name: Build PHP
              if: success()
              run: docker build -t docker.pkg.github.com/${REPO_LOWERCASE}/app_php:${IMAGE_TAG}
                --target armaforces_web_php -f .docker/Dockerfile .

            - name: Build Nginx
              if: success()
              run: docker build -t docker.pkg.github.com/${REPO_LOWERCASE}/app_nginx:${IMAGE_TAG}
                --target armaforces_web_nginx -f .docker/Dockerfile .

            - name: Push PHP
              if: success()
              uses: actions-hub/docker@master
              with:
                  args: push docker.pkg.github.com/${REPO_LOWERCASE}/app_php:${IMAGE_TAG}

            - name: Push Nginx
              if: success()
              uses: actions-hub/docker@master
              with:
                  args: push docker.pkg.github.com/${REPO_LOWERCASE}/app_nginx:${IMAGE_TAG}
