name: Docker registry

on:
    push:
        branches:
            - master
            - dev

env:
    REPO_LOWERCASE: armaforces/website

jobs:
    github:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   name: Login to registry
                uses: actions-hub/docker/login@master
                env:
                    DOCKER_USERNAME: ${{ github.actor }}
                    DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
                    DOCKER_REGISTRY_URL: docker.pkg.github.com

            -   name: Create VERSION
                run: echo $GITHUB_SHA > VERSION

            -   name: Build PHP
                if: success()
                run: docker build -t docker.pkg.github.com/${REPO_LOWERCASE}/app_php:${IMAGE_TAG}
                    --target armaforces_web_php -f .docker/Dockerfile .

            -   name: Build Nginx
                if: success()
                run: docker build -t docker.pkg.github.com/${REPO_LOWERCASE}/app_nginx:${IMAGE_TAG}
                    --target armaforces_web_nginx -f .docker/Dockerfile .

            -   name: Push PHP
                if: success()
                uses: actions-hub/docker@master
                with:
                    args: push docker.pkg.github.com/${REPO_LOWERCASE}/app_php:${IMAGE_TAG}

            -   name: Push Nginx
                if: success()
                uses: actions-hub/docker@master
                with:
                    args: push docker.pkg.github.com/${REPO_LOWERCASE}/app_nginx:${IMAGE_TAG}

            -   name: Update Dev Env PHP
                if: success() && github.ref == 'refs/heads/dev'
                uses: wei/curl@v1
                with:
                    args: -X POST ${{ secrets.WEBHOOK_UPDATE_PHP_DEV }}

            -   name: Update Dev Env Nginx
                if: success() && github.ref == 'refs/heads/dev'
                uses: wei/curl@v1
                with:
                    args: -X POST ${{ secrets.WEBHOOK_UPDATE_NGINX_DEV }}

            -   name: Update Prod Env PHP
                if: success() && github.ref == 'refs/heads/master'
                uses: wei/curl@v1
                with:
                    args: -X POST ${{ secrets.WEBHOOK_UPDATE_PHP_PROD }}

            -   name: Update Prod Env Nginx
                if: success() && github.ref == 'refs/heads/master'
                uses: wei/curl@v1
                with:
                    args: -X POST ${{ secrets.WEBHOOK_UPDATE_NGINX_PROD }}
