on: [ push ]

name: Lint
jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   uses: docker://jakzal/phpqa:1.42-php7.4-alpine
                name: PHP-CS-Fixer
                with:
                    args: php-cs-fixer fix --diff --dry-run
