on: [push, pull_request]

name: Lint
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: docker://oskarstark/php-cs-fixer-ga
        name: PHP-CS-Fixer
        with:
          args: --diff --dry-run
