on: [ push ]

name: Security
jobs:
    security-checker:
        name: Symfony Security Checker
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: symfonycorp/security-checker-action@v2
