on: [ pull_request ]

name: Tests
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout branch
                uses: actions/checkout@v2

            -   name: Install dependencies
                uses: MilesChou/composer-action/7.4/install@master
                with:
                    args: install

            -   name: Run tests
                uses: php-actions/phpunit@v9
                with:
                    configuration: phpunit.xml.dist
                    args: --testdox
